# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - git config --global user.name "lichess-mechanical-user"
      - git config --global user.email ""
      - git clone https://$GIT_TOKEN@github.com/OuKevin/lichess-puzzle-rating-tracker-api.git
      - git remote rm origin
      - git remote add origin https://$GIT_TOKEN@github.com/OuKevin/lichess-puzzle-rating-tracker-api.git
      - git fetch --all
      - git checkout master
      - git status
      
      - npm ci
      - npm run bootstrap:ci
      - npm run build:ci
      - npm run publish
      - npm run version

  post_build:
    commands:
      - npm version patch -m 'code build version bump'
      - git push --set-upstream origin master
      - git push origin refs/tags/*:refs/tags/*
